### ISSUE TITLE
Platform dependency PHP 7.1

### ISSUE THREAD

**Issue by dol** [leofeyer/optimize-native-functions-fixer#1]
The composer dependency states a minimal version of PHP 7.1. Could you lower this or remove it?

**Comment by leofeyer** [comment]
Which PHP version are you using?

**Comment by dol** [comment]
Depending on the project: PHP 5.6 and PHP 7.0.
The issue is void and https://secure.php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration

**Comment by leofeyer** [comment]
Are you aware that this optimization only works in PHP 7? Therefore I don't think we need to support PHP 5.6. I will check PHP 7.0 support.

**Comment by leofeyer** [comment]
I have adjusted the PHP version constraint in fb8650dedcfcad4ff64678c7b1e5080dc5383a9b.

**Comment by leofeyer** [comment]
@dol Version 1.1 supports PHP 5.6 and PHP 7.0+ now.

**Comment by dol** [comment]
Yeah. :tada: 
Thank you. I wanted to say even if optimizations are only for PHP 7.0 it's possible to have a local cli environment with PHP 5.6 that's performing the fixes.
But this comment is now obsolete due to your new release. Thank you.

**Comment by leofeyer** [comment]
You are welcome. 😉
